/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Patient;

/**
 *
 * @author amirp
 */
public class ViewJPanel extends javax.swing.JPanel {

    ImageIcon profilePicture;
    Patient p1;
    
    public ViewJPanel() {
        initComponents();
    }
    
    public ViewJPanel(Patient p1) {
        this.p1 = p1;
        initComponents();
        populateData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        age = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        lastname = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        phone = new javax.swing.JTextField();
        other = new javax.swing.JRadioButton();
        first_name = new javax.swing.JLabel();
        imgUploader_label = new javax.swing.JLabel();
        last_name = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        gender_label = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();
        phone_label = new javax.swing.JLabel();
        sign_up = new javax.swing.JButton();
        PatinetLabel = new javax.swing.JLabel();
        patientType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        jPanel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        age.setEditable(false);

        firstname.setEditable(false);
        firstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        gender.add(male);
        male.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        male.setText("Male");
        male.setActionCommand("male");

        lastname.setEditable(false);
        lastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });

        gender.add(female);
        female.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        female.setText("Female");
        female.setActionCommand("female");

        phone.setEditable(false);
        phone.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        gender.add(other);
        other.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        other.setText("Prefer not to say");
        other.setActionCommand("other");

        first_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        first_name.setText("First Name:");

        imgUploader_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        imgUploader_label.setText("Upload Your Photo Here:");

        last_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        last_name.setText("Last Name:");

        img.setPreferredSize(new java.awt.Dimension(50, 50));

        gender_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        gender_label.setText("I am a:");

        age_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        age_label.setText("Age:");

        phone_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        phone_label.setText("Phone Number:");

        sign_up.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        sign_up.setText("Sign Up");
        sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_upActionPerformed(evt);
            }
        });

        PatinetLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        PatinetLabel.setText("Patient Type:");

        patientType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appoinment", "Walk-In" }));
        patientType.setSelectedIndex(-1);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel2.setText("Patinet Information");

        email_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        email_label.setText("Email:");

        email.setEditable(false);
        email.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(email))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PatinetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age)
                            .addComponent(phone)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(other)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(patientType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(imgUploader_label, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gender_label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addComponent(lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                    .addContainerGap(313, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(other)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientType, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PatinetLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_label)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(imgUploader_label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(492, 492, 492)
                .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(last_name))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gender_label))
                    .addContainerGap(325, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_upActionPerformed

        try{
            String name = (this.firstname.getText()) + " " + (this.lastname.getText());
            String gender_var = (this.gender.getSelection().getActionCommand());
            String age_var = (this.age.getText());
            String phone_var = (this.phone.getText());
            String email_var = (this.email.getText());
            String patient_type = this.patientType.getSelectedItem().toString();
            String message = "Name: " + name + System.lineSeparator() + "Gender: " + gender_var  + System.lineSeparator() + "Patient Type: " + patient_type  + System.lineSeparator() + "Age: " + age_var + " years old"  + System.lineSeparator() + "Phone Number: " + phone_var + System.lineSeparator() + "Email: " + email_var;

            if(name.equals("")){
                message = "Enter Your Name Please";
            }

            else if(age_var.equals("")){
                message = "Enter Your Age Please";
            }

            else if(email_var.equals("")){
                message = "Enter Your Email Please";
            }

            else if(phone_var.equals("")){
                message = "Enter Your Phone Please";
            }
            JOptionPane.showMessageDialog(this, message, "Success", HEIGHT, profilePicture);

        }

        catch(NullPointerException ne){
            String errormsg = "Please fill out all of the information";
            JOptionPane.showMessageDialog(this,errormsg);
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(this, "");
        }
    }//GEN-LAST:event_sign_upActionPerformed

    public void populateData(){
        this.firstname.setText(p1.getFname());
        this.lastname.setText(p1.getLname());
        String sex = p1.getGender();
        if(sex.equals("male")){
            this.gender.setSelected(this.male.getModel(), true);
        }else if(sex.equals("female")){
            this.gender.setSelected(this.female.getModel(), true);
        }else{
            this.gender.setSelected(this.other.getModel(), true);
        }
        this.age.setText(p1.getAge());
        this.phone.setText(p1.getPhone());
        this.email.setText(p1.getEmail());
        this.img.setIcon(p1.getProfilePicture());
        this.patientType.setSelectedItem(p1.getPatient_type());
        this.male.setEnabled(false);
        this.female.setEnabled(false);
        this.other.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PatinetLabel;
    private javax.swing.JTextField age;
    private javax.swing.JLabel age_label;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_label;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel first_name;
    private javax.swing.JTextField firstname;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel gender_label;
    private javax.swing.JLabel img;
    private javax.swing.JLabel imgUploader_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel last_name;
    private javax.swing.JTextField lastname;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton other;
    private javax.swing.JComboBox<String> patientType;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phone_label;
    private javax.swing.JButton sign_up;
    // End of variables declaration//GEN-END:variables
}
